#pragma warning(disable:4244)
#pragma warning(disable:4267)

#include "component.h"


using namespace std;

COMPONENT_TYPE Component::GetType() const {
    return type;
}

void Component::SetType(COMPONENT_TYPE type) {
    this->type = type;
}

shared_ptr<Component> CreateComponent(COMPONENT_TYPE type) {
    switch (type) {
    case COMPONENT_COMMUNITY:
        return LM_NEW(CommunityComponent);
    case COMPONENT_HOTEL:
        return LM_NEW(HotelComponent);
    case COMPONENT_MALL:
        return LM_NEW(MallComponent);
    case COMPONENT_SHOP:
        return LM_NEW(ShopComponent);
    case COMPONENT_RESTAURANT:
        return LM_NEW(RestaurantComponent);
    case COMPONENT_CARRENT:
        return LM_NEW(CarRentComponent);
    case COMPONENT_THEATER:
        return LM_NEW(TheaterComponent);
    case COMPONENT_CINEMA:
        return LM_NEW(CinemaComponent);
    case COMPONENT_MUSEUM:
        return LM_NEW(MuseumComponent);
    case COMPONENT_MASAGE:
        return LM_NEW(MasageComponent);
    case COMPONENT_PACKAGE:
        return LM_NEW(PackageComponent);
    case COMPONENT_OFFICE:
        return LM_NEW(OfficeComponent);
    case COMPONENT_FURNISH:
        return LM_NEW(FurnishComponent);
    case COMPONENT_MOVING:
        return LM_NEW(MovingComponent);
    case COMPONENT_OPERATOR:
        return LM_NEW(OperatorComponent);
    case COMPONENT_GAME:
        return LM_NEW(GameComponent);
    case COMPONENT_LEASE:
        return LM_NEW(LeaseComponent);
    case COMPONENT_FINANCE:
        return LM_NEW(FinanceComponent);
    case COMPONENT_LENDING:
        return LM_NEW(LendingComponent);
    case COMPONENT_SALE:
        return LM_NEW(SaleComponent);
    case COMPONENT_MEDICAL:
        return LM_NEW(MedicalComponent);
    case COMPONENT_RELATION:
        return LM_NEW(RelationComponent);
    case COMPONENT_ESHOP:
        return LM_NEW(EshopComponent);
    case COMPONENT_STAR:
        return LM_NEW(StarComponent);
    case COMPONENT_ENGINEER:
        return LM_NEW(EngineerComponent);
    case COMPONENT_CONSTRUCT:
        return LM_NEW(ConstructComponent);
    case COMPONENT_ART:
        return LM_NEW(ArtComponent);
    case COMPONENT_PUBLISHER:
        return LM_NEW(PublisherComponent);
    case COMPONENT_TRAVEL:
        return LM_NEW(TravelComponent);
    case COMPONENT_MEDIA:
        return LM_NEW(MediaComponent);
    case COMPONENT_LAWYER:
        return LM_NEW(LawyerComponent);
    case COMPONENT_CREW:
        return LM_NEW(CrewComponent);
    case COMPONENT_INSURANCE:
        return LM_NEW(InsuranceComponent);
    case COMPONENT_SECURITY:
        return LM_NEW(SecurityComponent);
    case COMPONENT_CLEANING:
        return LM_NEW(CleaningComponent);
    case COMPONENT_GREEN:
        return LM_NEW(GreenComponent);
    case COMPONENT_INTERMEDIARY:
        return LM_NEW(IntermediaryComponent);
    case COMPONENT_LAB:
        return LM_NEW(LabComponent);
    case COMPONENT_GOVERNMENT:
        return LM_NEW(GovernmentComponent);
    case COMPONENT_EDUCATIONDEPT:
        return LM_NEW(EducationDeptComponent);
    case COMPONENT_INFODEPT:
        return LM_NEW(InfoDeptComponent);
    case COMPONENT_FINANCEDEPT:
        return LM_NEW(FinanceDeptComponent);
    case COMPONENT_TRADEDEPT:
        return LM_NEW(TradeDeptComponent);
    case COMPONENT_PETITIONDEPT:
        return LM_NEW(PetitionDeptComponent);
    case COMPONENT_WEATHERDEPT:
        return LM_NEW(WeatherDeptComponent);
    case COMPONENT_TAXDEPT:
        return LM_NEW(TaxDeptComponent);
    case COMPONENT_CIVILDEPT:
        return LM_NEW(CivilDeptComponent);
    case COMPONENT_SCIENCEDEPT:
        return LM_NEW(ScienceDeptComponent);
    case COMPONENT_ENGINEERDEPT:
        return LM_NEW(EngineerDeptComponent);
    case COMPONENT_SOCIALDEPT:
        return LM_NEW(SocialDeptComponent);
    case COMPONENT_DOGE:
        return LM_NEW(DogeComponent);
    case COMPONENT_COMMITTEE:
        return LM_NEW(CommitteeComponent);
    case COMPONENT_FACTORY:
        return LM_NEW(FactoryComponent);
    case COMPONENT_RESOURCE:
        return LM_NEW(ResourceComponent);
    case COMPONENT_PARK:
        return LM_NEW(ParkComponent);
    case COMPONENT_PLAZA:
        return LM_NEW(PlazaComponent);
    case COMPONENT_STATUE:
        return LM_NEW(StatueComponent);
    case COMPONENT_ZOO:
        return LM_NEW(ZooComponent);
    case COMPONENT_BOTANIC:
        return LM_NEW(BotanicComponent);
    case COMPONENT_AQUARIUM:
        return LM_NEW(AquariumComponent);
    case COMPONENT_AMUSEMENT:
        return LM_NEW(AmusementComponent);
    case COMPONENT_GYM:
        return LM_NEW(GymComponent);
    case COMPONENT_STADIUM:
        return LM_NEW(StadiumComponent);
    case COMPONENT_RESORT:
        return LM_NEW(ResortComponent);
    case COMPONENT_REMAINS:
        return LM_NEW(RemainsComponent);
    case COMPONENT_KINDER:
        return LM_NEW(KinderComponent);
    case COMPONENT_PRIMARY:
        return LM_NEW(PrimaryComponent);
    case COMPONENT_MIDDLE:
        return LM_NEW(MiddleComponent);
    case COMPONENT_UNIVERSITY:
        return LM_NEW(UniversityComponent);
    case COMPONENT_VOCATIONAL:
        return LM_NEW(VocationalComponent);
    case COMPONENT_CLINIC:
        return LM_NEW(ClinicComponent);
    case COMPONENT_HOSPITAL:
        return LM_NEW(HospitalComponent);
    case COMPONENT_INPATIENT:
        return LM_NEW(InpatientComponent);
    case COMPONENT_SANATORIUM:
        return LM_NEW(SanatoriumComponent);
    case COMPONENT_POLICE:
        return LM_NEW(PoliceComponent);
    case COMPONENT_PRISON:
        return LM_NEW(PrisonComponent);
    case COMPONENT_FIRE:
        return LM_NEW(FireComponent);
    case COMPONENT_COURT:
        return LM_NEW(CourtComponent);
    case COMPONENT_TVSTATION:
        return LM_NEW(TVStationComponent);
    case COMPONENT_POST:
        return LM_NEW(PostComponent);
    case COMPONENT_BANK:
        return LM_NEW(BankComponent);
    case COMPONENT_STOCK:
        return LM_NEW(StockComponent);
    case COMPONENT_LIBRARY:
        return LM_NEW(LibraryComponent);
    case COMPONENT_ROADFIX:
        return LM_NEW(RoadFixComponent);
    case COMPONENT_GASOLINE:
        return LM_NEW(GasolineComponent);
    case COMPONENT_CREMATORIUM:
        return LM_NEW(CrematoriumComponent);
    case COMPONENT_CEMETRY:
        return LM_NEW(CemeteryComponent);
    case COMPONENT_WATER:
        return LM_NEW(WaterComponent);
    case COMPONENT_SEWAGE:
        return LM_NEW(SewageComponent);
    case COMPONENT_POWER:
        return LM_NEW(PowerComponent);
    case COMPONENT_WINDMILL:
        return LM_NEW(WindmillComponent);
    case COMPONENT_NUCLEAR:
        return LM_NEW(NuclearComponent);
    case COMPONENT_BATTERY:
        return LM_NEW(BatteryComponent);
    case COMPONENT_DATA:
        return LM_NEW(DataComponent);
    case COMPONENT_RECYCLE:
        return LM_NEW(RecycleComponent);
    case COMPONENT_TRASH:
        return LM_NEW(TrashComponent);
    case COMPONENT_INCINERATION:
        return LM_NEW(IncinerationComponent);
    case COMPONENT_DEVICE:
        return LM_NEW(DeviceComponent);
    case COMPONENT_PARKING:
        return LM_NEW(ParkingComponent);
    case COMPONENT_GUARD:
        return LM_NEW(GuardComponent);
    case COMPONENT_TOILET:
        return LM_NEW(ToiletComponent);
    case COMPONENT_CANTEEN:
        return LM_NEW(CanteenComponent);
    case COMPONENT_DORMITRY:
        return LM_NEW(DormitoryComponent);
    case COMPONENT_PLAYGROUND:
        return LM_NEW(PlaygroundComponent);
    case COMPONENT_STATION:
        return LM_NEW(StationComponent);
    default:
        break;
    }

    return nullptr;
}
