#pragma warning(disable:4244)
#pragma warning(disable:4267)

#include "organization.h"


using namespace std;

ORGANIZATION_TYPE Organization::GetType() const {
    return type;
}

void Organization::SetType(ORGANIZATION_TYPE type) {
    this->type = type;
}

shared_ptr<Organization> CreateOrganization(ORGANIZATION_TYPE type) {
    switch (type) {
    case ORGANIZATION_COMMUNITY:
        return LM_NEW(CommunityOrganization);
    case ORGANIZATION_HOTEL:
        return LM_NEW(HotelOrganization);
    case ORGANIZATION_MALL:
        return LM_NEW(MallOrganization);
    case ORGANIZATION_SHOP:
        return LM_NEW(ShopOrganization);
    case ORGANIZATION_RESTAURANT:
        return LM_NEW(RestaurantOrganization);
    case ORGANIZATION_CARRENT:
        return LM_NEW(CarRentOrganization);
    case ORGANIZATION_THEATER:
        return LM_NEW(TheaterOrganization);
    case ORGANIZATION_CINEMA:
        return LM_NEW(CinemaOrganization);
    case ORGANIZATION_MUSEUM:
        return LM_NEW(MuseumOrganization);
    case ORGANIZATION_MASAGE:
        return LM_NEW(MasageOrganization);
    case ORGANIZATION_PACKAGE:
        return LM_NEW(PackageOrganization);
    case ORGANIZATION_OFFICE:
        return LM_NEW(OfficeOrganization);
    case ORGANIZATION_FURNISH:
        return LM_NEW(FurnishOrganization);
    case ORGANIZATION_MOVING:
        return LM_NEW(MovingOrganization);
    case ORGANIZATION_OPERATOR:
        return LM_NEW(OperatorOrganization);
    case ORGANIZATION_GAME:
        return LM_NEW(GameOrganization);
    case ORGANIZATION_LEASE:
        return LM_NEW(LeaseOrganization);
    case ORGANIZATION_FINANCE:
        return LM_NEW(FinanceOrganization);
    case ORGANIZATION_LENDING:
        return LM_NEW(LendingOrganization);
    case ORGANIZATION_SALE:
        return LM_NEW(SaleOrganization);
    case ORGANIZATION_MEDICAL:
        return LM_NEW(MedicalOrganization);
    case ORGANIZATION_RELATION:
        return LM_NEW(RelationOrganization);
    case ORGANIZATION_ESHOP:
        return LM_NEW(EshopOrganization);
    case ORGANIZATION_STAR:
        return LM_NEW(StarOrganization);
    case ORGANIZATION_ENGINEER:
        return LM_NEW(EngineerOrganization);
    case ORGANIZATION_CONSTRUCT:
        return LM_NEW(ConstructOrganization);
    case ORGANIZATION_ART:
        return LM_NEW(ArtOrganization);
    case ORGANIZATION_PUBLISHER:
        return LM_NEW(PublisherOrganization);
    case ORGANIZATION_TRAVEL:
        return LM_NEW(TravelOrganization);
    case ORGANIZATION_MEDIA:
        return LM_NEW(MediaOrganization);
    case ORGANIZATION_LAWYER:
        return LM_NEW(LawyerOrganization);
    case ORGANIZATION_CREW:
        return LM_NEW(CrewOrganization);
    case ORGANIZATION_INSURANCE:
        return LM_NEW(InsuranceOrganization);
    case ORGANIZATION_SECURITY:
        return LM_NEW(SecurityOrganization);
    case ORGANIZATION_CLEANING:
        return LM_NEW(CleaningOrganization);
    case ORGANIZATION_GREEN:
        return LM_NEW(GreenOrganization);
    case ORGANIZATION_INTERMEDIARY:
        return LM_NEW(IntermediaryOrganization);
    case ORGANIZATION_LAB:
        return LM_NEW(LabOrganization);
    case ORGANIZATION_GOVERNMENT:
        return LM_NEW(GovernmentOrganization);
    case ORGANIZATION_EDUCATIONDEPT:
        return LM_NEW(EducationDeptOrganization);
    case ORGANIZATION_INFODEPT:
        return LM_NEW(InfoDeptOrganization);
    case ORGANIZATION_FINANCEDEPT:
        return LM_NEW(FinanceDeptOrganization);
    case ORGANIZATION_TRADEDEPT:
        return LM_NEW(TradeDeptOrganization);
    case ORGANIZATION_PETITIONDEPT:
        return LM_NEW(PetitionDeptOrganization);
    case ORGANIZATION_WEATHERDEPT:
        return LM_NEW(WeatherDeptOrganization);
    case ORGANIZATION_TAXDEPT:
        return LM_NEW(TaxDeptOrganization);
    case ORGANIZATION_CIVILDEPT:
        return LM_NEW(CivilDeptOrganization);
    case ORGANIZATION_SCIENCEDEPT:
        return LM_NEW(ScienceDeptOrganization);
    case ORGANIZATION_ENGINEERDEPT:
        return LM_NEW(EngineerDeptOrganization);
    case ORGANIZATION_SOCIALDEPT:
        return LM_NEW(SocialDeptOrganization);
    case ORGANIZATION_DOGE:
        return LM_NEW(DogeOrganization);
    case ORGANIZATION_COMMITTEE:
        return LM_NEW(CommitteeOrganization);
    case ORGANIZATION_FACTORY:
        return LM_NEW(FactoryOrganization);
    case ORGANIZATION_RESOURCE:
        return LM_NEW(ResourceOrganization);
    case ORGANIZATION_PARK:
        return LM_NEW(ParkOrganization);
    case ORGANIZATION_PLAZA:
        return LM_NEW(PlazaOrganization);
    case ORGANIZATION_STATUE:
        return LM_NEW(StatueOrganization);
    case ORGANIZATION_ZOO:
        return LM_NEW(ZooOrganization);
    case ORGANIZATION_BOTANIC:
        return LM_NEW(BotanicOrganization);
    case ORGANIZATION_AQUARIUM:
        return LM_NEW(AquariumOrganization);
    case ORGANIZATION_AMUSEMENT:
        return LM_NEW(AmusementOrganization);
    case ORGANIZATION_GYM:
        return LM_NEW(GymOrganization);
    case ORGANIZATION_STADIUM:
        return LM_NEW(StadiumOrganization);
    case ORGANIZATION_RESORT:
        return LM_NEW(ResortOrganization);
    case ORGANIZATION_REMAINS:
        return LM_NEW(RemainsOrganization);
    case ORGANIZATION_KINDER:
        return LM_NEW(KinderOrganization);
    case ORGANIZATION_PRIMARY:
        return LM_NEW(PrimaryOrganization);
    case ORGANIZATION_MIDDLE:
        return LM_NEW(MiddleOrganization);
    case ORGANIZATION_UNIVERSITY:
        return LM_NEW(UniversityOrganization);
    case ORGANIZATION_VOCATIONAL:
        return LM_NEW(VocationalOrganization);
    case ORGANIZATION_CLINIC:
        return LM_NEW(ClinicOrganization);
    case ORGANIZATION_HOSPITAL:
        return LM_NEW(HospitalOrganization);
    case ORGANIZATION_INPATIENT:
        return LM_NEW(InpatientOrganization);
    case ORGANIZATION_SANATORIUM:
        return LM_NEW(SanatoriumOrganization);
    case ORGANIZATION_POLICE:
        return LM_NEW(PoliceOrganization);
    case ORGANIZATION_PRISON:
        return LM_NEW(PrisonOrganization);
    case ORGANIZATION_FIRE:
        return LM_NEW(FireOrganization);
    case ORGANIZATION_COURT:
        return LM_NEW(CourtOrganization);
    case ORGANIZATION_TVSTATION:
        return LM_NEW(TVStationOrganization);
    case ORGANIZATION_POST:
        return LM_NEW(PostOrganization);
    case ORGANIZATION_BANK:
        return LM_NEW(BankOrganization);
    case ORGANIZATION_STOCK:
        return LM_NEW(StockOrganization);
    case ORGANIZATION_LIBRARY:
        return LM_NEW(LibraryOrganization);
    case ORGANIZATION_ROADFIX:
        return LM_NEW(RoadFixOrganization);
    case ORGANIZATION_GASOLINE:
        return LM_NEW(GasolineOrganization);
    case ORGANIZATION_CREMATORIUM:
        return LM_NEW(CrematoriumOrganization);
    case ORGANIZATION_CEMETRY:
        return LM_NEW(CemeteryOrganization);
    case ORGANIZATION_WATER:
        return LM_NEW(WaterOrganization);
    case ORGANIZATION_SEWAGE:
        return LM_NEW(SewageOrganization);
    case ORGANIZATION_POWER:
        return LM_NEW(PowerOrganization);
    case ORGANIZATION_WINDMILL:
        return LM_NEW(WindmillOrganization);
    case ORGANIZATION_NUCLEAR:
        return LM_NEW(NuclearOrganization);
    case ORGANIZATION_BATTERY:
        return LM_NEW(BatteryOrganization);
    case ORGANIZATION_DATA:
        return LM_NEW(DataOrganization);
    case ORGANIZATION_RECYCLE:
        return LM_NEW(RecycleOrganization);
    case ORGANIZATION_TRASH:
        return LM_NEW(TrashOrganization);
    case ORGANIZATION_INCINERATION:
        return LM_NEW(IncinerationOrganization);
    case ORGANIZATION_DEVICE:
        return LM_NEW(DeviceOrganization);
    case ORGANIZATION_PARKING:
        return LM_NEW(ParkingOrganization);
    case ORGANIZATION_GUARD:
        return LM_NEW(GuardOrganization);
    case ORGANIZATION_TOILET:
        return LM_NEW(ToiletOrganization);
    case ORGANIZATION_CANTEEN:
        return LM_NEW(CanteenOrganization);
    case ORGANIZATION_DORMITRY:
        return LM_NEW(DormitoryOrganization);
    case ORGANIZATION_PLAYGROUND:
        return LM_NEW(PlaygroundOrganization);
    case ORGANIZATION_STATION:
        return LM_NEW(StationOrganization);
    default:
        break;
    }

    return nullptr;
}
